Repository publiclab/leaflet-environmental-layers, pull requests merged in 2018-11, with the labels that each got.

#77 Added the Indigenous Lands **Territories** Layer. Indigenous Lands Territories Inventory
  dist/LeafletEnvironmentalLayers.js
  example/index.html
  src/indigenousLandsTerritoriesLayer.js
  src/leafletEnvironmentalLayers.js
Labels: ready

#76 Added Indigenous Lands **Languages** Layer. Indigenous Lands Languages Inventory
  dist/LeafletEnvironmentalLayers.js
  example/index.html
  src/indigenousLandsLanguagesLayer.js
  src/leafletEnvironmentalLayers.js
Labels: ready

#78 Added Indigenous Lands **Treaties** Layer. Indigenous Lands Treaties Inventory
  dist/LeafletEnvironmentalLayers.js
  example/index.html
  src/indigenousLandsTreatiesLayer.js
  src/leafletEnvironmentalLayers.js
Labels: ready

#79 Added a prototype for aqicnLayer and tileLayer
  dist/LeafletEnvironmentalLayers.css
  dist/LeafletEnvironmentalLayers.js
  example/index.html
  src/aqicnLayer.js
  src/leafletEnvironmentalLayers.js
Labels: ready

#81 Spinner added while fetching data .
  dist/LeafletEnvironmentalLayers.js
  example/index.html
  package-lock.json
  package.json
  src/fractracker.js
  src/indigenousLandsLanguagesLayer.js
  src/indigenousLandsTerritoriesLayer.js
  src/indigenousLandsTreatiesLayer.js
  src/mapKnitterLayer.js
  src/odorReportLayer.js
  src/purpleAirMarkerLayer.js
  src/purpleLayer.js
  src/skyTruthLayer.js
  src/toxicReleaseLayer.js
Labels: in progress, review me

#80 Overload with PurpleAir layer when viewing whole world - Solved #41
  dist/LeafletEnvironmentalLayers.js
  src/purpleAirMarkerLayer.js
Labels: in progress, review me

#82 Version bump 1.1.1
  example/index.html
  package.json
Labels: in progress

#83 [Bug Fix] self used to call map object .
  dist/LeafletEnvironmentalLayers.js
  src/aqicnLayer.js
  src/fractracker.js
  src/indigenousLandsLanguagesLayer.js
  src/indigenousLandsTerritoriesLayer.js
  src/indigenousLandsTreatiesLayer.js
  src/mapKnitterLayer.js
  src/odorReportLayer.js
  src/purpleAirMarkerLayer.js
  src/purpleLayer.js
  src/skyTruthLayer.js
  src/toxicReleaseLayer.js
Labels: in progress

#84 patch version bump .
  package.json
Labels: in progress

#85 Update README.md
  README.md
Labels: in progress

#86 ability to generate permalink with url hash of currently enabled layers #33
  example/index.html
  package-lock.json
  package.json
Labels: in progress

#91 mobile fractracker layer added
  README.md
  example/index.html
Labels: in progress

#92 Wisconsin Non metallic layer added
  README.md
  example/index.html
Labels: in progress
