Repository publiclab/leaflet-environmental-layers, pull requests merged in 2020-03, with the labels that each got.

#430 Layers browser width calculated based on map width
  dist/LeafletEnvironmentalLayers.css
  dist/LeafletEnvironmentalLayers.js
  example/layers.js
  example/oneLinerCodeExample.html
  spec/javascripts/basicImplementation.spec.js
  src/AllLayers.js
  src/util/layersBrowser.js
Labels: needs-rebase

#417 Add icon for broken layer
  cypress/integration/layerErrorIcon.spec.js
  cypress/integration/pfasLayer.spec.js
  dist/LeafletEnvironmentalLayers.js
  example/layers.js
  src/AllLayers.js
  src/aqicnLayer.js
  src/eonetFiresLayer.js
  src/fracTrackerMobileLayer.js
  src/indigenousLayers.js
  src/info.json
  src/layercode.js
  src/osmLandfillMineQuarryLayer.js
  src/pfasLayer.js
  src/purpleLayer.js
  src/toxicReleaseLayer.js
  src/unearthing.js
  src/util/layerError.js
  src/util/layersBrowser.js
  src/wisconsinLayer.js
Labels: ready

#428 Highlight new layers
  cypress/integration/layersMenu.spec.js
  cypress/integration/odorreport.spec.js
  cypress/integration/skytruth.spec.js
  cypress/integration/toxicRelease.spec.js
  dist/LeafletEnvironmentalLayers.js
  example/index.html
  example/multipleMaps.html
  example/oneLinerCodeExample.html
  src/util/layersBrowser.js
Labels: ready

#443 Fix bugs caused by layer id conflict
  cypress/integration/aqicn.spec.js
  cypress/integration/eonetFiresLayer.spec.js
  cypress/integration/fractracker.spec.js
  cypress/integration/fractrackerMobile.spec.js
  cypress/integration/layerErrorIcon.spec.js
  cypress/integration/layerFilter.spec.js
  cypress/integration/layersMenu.spec.js
  cypress/integration/luftdaten.spec.js
  cypress/integration/odorreport.spec.js
  cypress/integration/openaq.spec.js
  cypress/integration/opensense.spec.js
  cypress/integration/osmLandfill.spec.js
  cypress/integration/pfasLayer.spec.js
  cypress/integration/purpleAirMarker.spec.js
  cypress/integration/purpleLayer.spec.js
  cypress/integration/skytruth.spec.js
  cypress/integration/toxicRelease.spec.js
  cypress/integration/unearthing.spec.js
  dist/LeafletEnvironmentalLayers.js
  spec/javascripts/basicImplementation.spec.js
  src/AllLayers.js
  src/util/layerError.js
  src/util/layersBrowser.js
Labels: ready, review me
